#####set the working directory
setwd("~/Nextcloud/Documents/HRS data")

#setup the packages
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(tidyr)
library(reshape2) 
library(weights)
library(haven)
library(psych)
library(corrplot)
library(ggplot2)
library(car)
library(mifa)
library(GPArotation)
library(TraMineR)
library(ggseqplot)
library(survey)
library(epitools)
library(tidyverse)
library(merTools)
library(magrittr)
library(ggeffects)
library(lme4)
library(splines)
library(broom)
library(ggthemes)
library(cobalt)
library(scales) 
library(seqHMM)
library(cluster)
library(WeightedCluster)
library(survival)
library(tableone)
library(survminer)
library(tidycmprsk)
library(ggsurvfit)
library(ecodist)
library(viridis)
library(gridExtra)
library(timereg)


###load the data
G2A <- read_dta("H_HRS_d_stata/H_HRS_d.dta")
RAND <- read_dta("randhrs1992_2020v1_STATA/randhrs1992_2020v1.dta")